{% set name = "hxntools" %}
{% set version = "0.5.1" %}
{% set sha256 = "fff2f2e1701a58a690ebd75389a5d8cc0e8ee0f767e64cead9e01ed2d1cbbca5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II-HXN/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bluesky
    - boltons
    - cycler
    - databroker
    - h5py
    - matplotlib
    - nslsii
    - numpy
    - ophyd
    - pandas
    - pyepics
    - scipy

test:
  imports:
    - hxntools

about:
  home: https://github.com/NSLS-II-HXN/hxntools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: NSLS-II Hard X-ray Nanoprobe data acquisition tools
